import Head from 'next/head';
import HeroBanner from '../components/HeroBanner';
import SearchExercises from '../components/SearchExercises';
import Exercises from '../components/Exercises';
import Loader from '../components/Loader';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Exercises App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <HeroBanner />
      <SearchExercises />
      <Exercises />
    </div>
  );
}
